### ISSUE TITLE
question about obtaining T2 with the brain only

### ISSUE THREAD

**Issue by xuesongle** [Jfortin1/EveTemplate#3]
Hi, @Jfortin1 

I notice that the way you obtain the T2 image with the brain only, one can use the convolution of the T2 and brain mask as follows:
eve_t2_brain <- eve_t2*eve_brain_mask

The question is that if eve_brain_mask is obtained in T1 space, do you need to register T2 to T1 image first, then apply the eve_brain_mask after?

Thanks.

**Comment by Jfortin1** [comment]
@xuesongle Thanks for asking, and yes you're correct, the images need to be registered. Something I forgot to mention: the modalities were already co-registered by the creators of the Eve Atlas , so no need for an additional registration. I'll add a note in the readme.md. Thanks!
