### ISSUE TITLE
Read in Eve Template as an antsImage

### ISSUE THREAD

**Issue by emsweene** [Jfortin1/EveTemplate#5]
Would be great to have the ability to read in the Eve template as an ```antsImage``` in order to work with ```ANTsR```.

**Comment by Jfortin1** [comment]
Check out `oro2ants` and `ants2oro` in `extransr` @muschellij2 
I would like to keep `EveTemplate` light and not depend on the `ANTsR` universe.

**Comment by emsweene** [comment]
Wonderful!  I will use this.

**Comment by muschellij2** [comment]
Agreed - if we had that for this package, then probably would have to
depend on ANTsRCore as a package, which would be a serious dependency to
add, so I agree that recommendation is best.
